/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    id("nebula.release") version "15.2.0"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://jcenter.bintray.com/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.projectlombok:lombok:1.18.18")
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.1")
}

group = "io.slugstack.oss"
// version = "0.0.14-SNAPSHOT"
description = "rewrite-definitions"
java.sourceCompatibility = JavaVersion.VERSION_11

publishing {
    repositories {
        maven {
            // name = "GitHubPackages"
            // url = uri("https://maven.pkg.github.com/OWNER/REPOSITORY")
            releaseRepo = uri("https://oss.sonatype.org/service/local/staging/deploy/maven2/")
            snapshotRepo = uri("https://oss.sonatype.org/content/repositories/snapshots/")
            url = snapshotRepo
            credentials {
                // username = project.findProperty("gpr.user") as String? ?: System.getenv("USERNAME")
                // password = project.findProperty("gpr.key") as String? ?: System.getenv("TOKEN")
                username = project.findProperty("ossrhUsername") as? String
                password = project.findProperty("ossrhPassword") as? String
            }
        }
    }

    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }

    // publications {
    //     register("gpr") {
    //         from(components["java"])
    //     }
    // }

}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
