---
name: update-gradle-wrapper

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch: {}

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          repo-token: ${{ github.token }}
